/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Avila24 (https://sketchfab.com/Avila24)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/nezuko-box-7c8b55ddad164e40ac02b6b56a8e7095
title: Nezuko Box
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Model(props) {
  const [firstLoading, setFirstLoading] = useState(true)
  const { nodes, materials } = useGLTF('/scene.gltf')
  const ref = useRef()

  setTimeout(() => {
    setFirstLoading(false)
  }, 1200)

  useFrame(() => {
    ref.current.rotation.y += 0.01
  })

  useFrame(() => {
    if (!firstLoading) return
    ref.current.rotation.y -= Math.random()
  })

  return (
    <group {...props} dispose={null} ref={ref}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[2.44, -4.46, 3.07]}>
              <mesh
                geometry={nodes.NezukoBox_NezukoBox_0.geometry}
                material={materials.NezukoBox}
              />
            </group>
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[2.44, -4.46, 3.07]}>
              <mesh
                geometry={nodes.Outline_Outline_0.geometry}
                material={materials.Outline}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
